# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
store = Bookstore.create(name: "Owl Be Back Bookstore")


Book.create!(title: "Harry Potter and the Sorcercer's Stone", author: "JK Rowling", genre: "fantasy", summary: "Harry Potter has no idea how famous he is. That's because he's being raised by his miserable aunt and uncle who are terrified Harry will learn that he's really a wizard, just as his parents were. But everything changes when Harry is summoned to attend an infamous school for wizards, and he begins to discover some clues about his illustrious birthright. From the surprising way he is greeted by a lovable giant, to the unique curriculum and colorful faculty at his unusual school, Harry finds himself drawn deep inside a mystical world he never knew existed and closer to his own noble destiny.", price: 20.99, cover_url: "https://images-na.ssl-images-amazon.com/images/I/51HSkTKlauL._SX346_BO1,204,203,200_.jpg")
Book.create!(title: "Harry Potter and the Chamber of Secrets", author: "JK Rowling", genre: "fantasy", summary: "The Dursleys were so mean that hideous that summer that all Harry Potter wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. But just as he's packing his bags, Harry receives a warning from a strange, impish creature named Dobby who says that if Harry Potter returns to Hogwarts, disaster will strike.", price: 20.99, cover_url: "https://images-na.ssl-images-amazon.com/images/I/51jNORv6nQL._SX340_BO1,204,203,200_.jpg")
Book.create!(title: "Harry Potter and the Prisoner of Azkaban", author: "JK Rowling", genre: "fantasy", summary: "For twelve long years, the dread fortress of Azkaban held an infamous prisoner named Sirius Black. Convicted of killing thirteen people with a single curse, he was said to be the heir apparent to the Dark Lord, Voldemort.", price: 20.99, cover_url: "https://images-na.ssl-images-amazon.com/images/I/71s7RjLd3fL._SY606_.jpg")
Book.create!(title: "Harry Potter and the Goblet of Fire", author: "JK Rowling", genre: "fantasy", summary: "Harry Potter is midway through his training as a wizard and his coming of age. Harry wants to get away from the pernicious Dursleys and go to the International Quidditch Cup. He wants to find out about the mysterious event that's supposed to take place at Hogwarts this year, an event involving two other rival schools of magic, and a competition that hasn't happened for a hundred years. He wants to be a normal, fourteen-year-old wizard. But unfortunately for Harry Potter, he's not normal - even by wizarding standards. And in his case, different can be deadly.", price: 20.99, cover_url: "https://images-na.ssl-images-amazon.com/images/I/71ykU-RQ0nL._SY606_.jpg")
Book.create!(title: "Harry Potter and the Order of the Pheonix", author: "JK Rowling", genre: "fantasy", summary: "In his fifth year at Hogwart's, Harry faces challenges at every turn, from the dark threat of He-Who-Must-Not-Be-Named and the unreliability of the government of the magical world to the rise of Ron Weasley as the keeper of the Gryffindor Quidditch Team. Along the way he learns about the strength of his friends, the fierceness of his enemies, and the meaning of sacrifice.", price: 20.99, cover_url: "https://images-na.ssl-images-amazon.com/images/I/91TpLHDnuFL.jpg")
Book.create!(title: "Harry Potter and the Halfblood Prince", author: "JK Rowling", genre: "fantasy", summary: "The war against Voldemort is not going well; even the Muggles have been affected. Dumbledore is absent from Hogwarts for long stretches of time, and the Order of the Phoenix has already suffered losses. And yet . . . as with all wars, life goes on. Sixth-year students learn to Apparate. Teenagers flirt and fight and fall in love. Harry receives some extraordinary help in Potions from the mysterious Half-Blood Prince. And with Dumbledore's guidance, he seeks out the full, complex story of the boy who became Lord Voldemort -- and thus finds what may be his only vulnerability.", price: 20.99, cover_url: "https://images-na.ssl-images-amazon.com/images/I/71EwgGuAS9L._SY606_.jpg")
Book.create!(title: "Harry Potter and the Deathly Hallows", author: "JK Rowling", genre: "fantasy", summary: "The heart of Book 7 is a hero's mission--not just in Harry's quest for the Horcruxes, but in his journey from boy to man--and Harry faces more danger than that found in all six Book combined, from the direct threat of the Death Eaters and you-know-who, to the subtle perils of losing faith in himself. Attentive readers would do well to remember Dumbledore's warning about making the choice between 'what is right and what is easy,' and know that Rowling applies the same difficult principle to the conclusion of her series. While fans will find the answers to hotly speculated questions about Dumbledore, Snape, and you-know-who, it is a testament to Rowling's skill as a storyteller that even the most astute and careful reader will be taken by surprise.", price: 20.99, cover_url: "https://images-na.ssl-images-amazon.com/images/I/91-gMZT24AL.jpg")
Book.create!(title: "The Ruins on Stone Hill (Heroes of Ravenford Book 1)", author: "Jackson Tjota", genre: "mystery", summary: "Mix four young talented misfits with a town suddenly besieged by darkness. What do you get? Magic, mystery, and mayhem!", price: 0.01, cover_url: "https://m.media-amazon.com/images/I/91Wb5O8-zBL._AC_UL654_FMwebp_QL65_.jpg")
Book.create!(title: "From Breath and Ruin (Elements of Five Book 1)", author: "Carrie Ann Ryan", genre: "fantasy", summary: "Lyric must unlock all five elements before she can bring the two kingdoms together and save her friends...and herself.", price: 6.99 , cover_url: "https://m.media-amazon.com/images/I/91WDuO2axCL._AC_UL654_FMwebp_QL65_.jpg")
Book.create!(title: "Redemption (Memory Man series Book 5)", author: "Amos Decker", genre: "thriller", summary: "Detective Amos Decker discovers that a mistake he made as a rookie detective may have led to deadly consequences in the latest Memory Man thriller in David Baldacci's #1 New York Times bestselling series.", price: 14.99, cover_url: "https://m.media-amazon.com/images/I/91wJtQD8qiL._AC_UL654_FMwebp_QL65_.jpg")
Book.create!(title: "Next Level Basic: The Definitive Basic Bitch Handbook", author: "Stassi Schroeder", genre: "comedy", summary: "Discover how to embrace your best basic self in this laugh-out-loud funny guidebook from the breakout star of Bravo’s hit reality show Vanderpump Rules, perfect for fans of the relatable and entertaining Book by The Betches and Andi Dorfman.", price: 12.99, cover_url: "https://m.media-amazon.com/images/I/71on6NtPblL._AC_UL654_FMwebp_QL65_.jpg")
Book.create!(title: "Valley of Embers (The Landkist Saga Book 1)", author: "Steven Kelliher", genre: "fantasy", summary: "The War of Sages rages on, but the Landkist are rising.", price: 0.01, cover_url: "https://m.media-amazon.com/images/I/91Vh7qVTQtL._AC_UL654_FMwebp_QL65_.jpg")
Book.create!(title: "Darkest Days : Still Surviving", author: "Boyd Craven III", genre: "adventure", summary: "Wes, finding himself between a rock and a hard place, had to make an impossible decision, one he's not sure he can forgive himself for. In his journey to always make the right choices, he risks his morals and the safety of those around him. Knowing exactly how he got there and unable to change his decisions, he struggles to keep going day by day.Lance and Henry weren't working alone, and as more of the opposition group’s actions are showing them to be as evil and twisted as they first seemed. If that wasn’t enough, Wes is betrayed by a friend.Not one for letting others remain enslaved, Wes’s group decides to go on the offensive. With time running out, and dark forces moving on his family, he has to become more than a simple moonshiner and occasional poacher. He has to survive what’s to be some of his darkest days and keep his humanity.With Raider being the only sane one left, he must guide his human like he’s never had to before.", price: 0.01, cover_url: "https://m.media-amazon.com/images/I/91iQsfSpVHL._AC_UL654_FMwebp_QL65_.jpg")
Book.create!(title: "Chiara X", author: "Nate Stack", genre: "literature", summary: "Chiara's father, the dangerous Leader X is not only cruel, he's also a major threat to humanity. When an escape at a maximum security prison on the moon leads to a series of catastrophic events on earth, Chiara, a determined young woman in her twenties suspects her father’s involvement. To stop him, and to make amends for years of his brutal oppression she undertakes a difficult journey to seek the help of the Protectors—a group of genetically gifted, but emotionally challenged individuals who love and fight like family. Along the way, Chiara’s gifts are put the test as she slowly learns the truth behind her evil father’s global tyranny.", price: 5.01, cover_url: "https://prodimage.images-bn.com/pimages/2940162150589_p0_v10_s550x406.jpg")
Book.create!(title: "Buried Deep (Jessie Cole Book 4)", author: "T.R. Ragan", genre: "mystery", summary: "Lacey Geiger could be a very rich woman. If Jessie Cole can find her. The beneficiary of a sizable estate, Lacey vanished years ago after escaping an abusive childhood and is veiled now behind a new identity. Jessie has two weeks to find her. It’s enough time to discover that Lacey is hiding from so much more than anyone realized. But she isn’t the only one with secrets. And Jessie’s not the only one searching for the truth.", price: 5.99, cover_url: "https://m.media-amazon.com/images/I/91sZGpMueXL._AC_UL654_FMwebp_QL65_.jpg")
Book.create!(title: "Fortune Furlough (A Miss Fortune Mystery Book 14)", author: "Jana DeLeon", genre: "comedy", summary: "Fortune, Ida Belle, and Gertie are finally off to Florida on the vacation they’ve always talked about. Days filled with white sand, turquoise water, and fruity drinks are the only thing on the agenda. But when Gertie’s “hot date” turns up dead and she’s the number one suspect, they’re forced to hang up their bathing suits and shift to investigating mode.", price: 5.99, cover_url: "https://m.media-amazon.com/images/I/91fhr-LlEoL._AC_UL654_FMwebp_QL65_.jpg")
Book.create!(title: "From Breath and Ruin (Elements of Five Book 1)", author: "Robert Matzen and Luca Dotti", genre: "biography", summary: "Twenty-five years after her passing, Audrey Hepburn remains the most beloved of all Hollywood stars, known as much for her role as UNICEF ambassador as for films like Roman Holiday and Breakfast at Tiffany's. Several biographies have chronicled her stardom, but none has covered her intense experiences through five years of Nazi occupation in the Netherlands. According to her son, Luca Dotti. Audrey Hepburn's war included participation in the Dutch Resistance, working as a doctor's assistant during the battle of Arnhem, the brutal execution of her uncle, and the ordeal of the Hunger Winter of 1944. She also had to contend with the fact that her father was a Nazi agent and her mother was pro-Nazi for the first two years of the occupation. But the war years also brought triumphs as Audrey became Arnhem's most famous young ballerina. Audrey's own reminiscences, new interviews with people who knew her in the war, wartime diaries, and research in classified Dutch archives shed light on the riveting, untold story of Audrey Hepburn under fire in World War II. Also included is a section of color and black-and-white photos. Many of these images are from Audrey's personal collection and are published here for the first time.", price: 9.99, cover_url: "https://images-na.ssl-images-amazon.com/images/I/41mAX01ac9L.jpg")


ReadingChallenge.create!(book_title: "Harry Potter and the Order of the Pheonix", comment: "Enjoying the book", reading_date: "Apr 21 2019")
ReadingChallenge.create!(book_title: "Chiara X", comment: "Can't stop reading", reading_date: "Apr 22 2019")
ReadingChallenge.create!(book_title: "From Breath and Ruin (Elements of Five Book 1)", comment: "Great start to the book!", reading_date: "Apr 23 2019")
ReadingChallenge.create!(book_title: "Harry Potter and the Goblet of Fire)", comment: "Reading challenge ftw", reading_date: "Apr 24 2019")
ReadingChallenge.create!(book_title: "Fortune Furlough (A Miss Fortune Mystery Book 14)", comment: "Plot amazing so far.", reading_date: "Apr 25 2019")
ReadingChallenge.create!(book_title: "Buried Deep (Jessie Cole Book 4)", comment: "great book so far", reading_date: "Apr 26 2019")
ReadingChallenge.create!(book_title: "Redemption (Memory Man series Book 5)", comment: "I like book 4 more", reading_date: "Apr 27 2019")
ReadingChallenge.create!(book_title: "The Ruins on Stone Hill (Heroes of Ravenford Book 1)", comment: "deep and spiritual", reading_date: "Apr 28 2019")
ReadingChallenge.create!(book_title: "Harry Potter and the Halfblood Prince", comment: "what can I say, I'm a potter fan", reading_date: "Apr 29 2019")
ReadingChallenge.create!(book_title: "Harry Potter and the Sorcercer's Stone", comment: "reliving my childhood", reading_date: "Apr 30 2019")
ReadingChallenge.create!(book_title: "The Ruins on Stone Hill (Heroes of Ravenford Book 2)", comment: "love the continuation", reading_date: "May 01 2019")
ReadingChallenge.create!(book_title: "Next Level Basic: The Definitive Basic Bitch Handbook", comment: "the title lol", reading_date: "May 02 2019")
ReadingChallenge.create!(book_title: "Memoirs of a Geisha", comment: "amazing, just amazing", reading_date: "May 03 2019")
ReadingChallenge.create!(book_title: "Lord of the Flies", comment: "have to read this for school", reading_date: "May 04 2019")
ReadingChallenge.create!(book_title: "The Handmaid's Tale", comment: "woaw", reading_date: "May 05 2019")
ReadingChallenge.create!(book_title: "Where'd You Go, Bernadette", comment: "half way to my 30 books reading goal, awww yeah", reading_date: "May 06 2019")
ReadingChallenge.create!(book_title: "The Underground Railroad", comment: "very informative, a look into the past", reading_date: "May 07 2019")
ReadingChallenge.create!(book_title: "Beartown", comment: "i hate bear even more after this", reading_date: "May 08 2019")
ReadingChallenge.create!(book_title: "White Oleander", comment: "great", reading_date: "May 09 2019")
ReadingChallenge.create!(book_title: "Speak", comment: "another book done", reading_date: "May 10 2019")
ReadingChallenge.create!(book_title: "A Wrinkle in Time", comment: "so gooodd", reading_date: "May 11 2019")
ReadingChallenge.create!(book_title: "The Grey King", comment: "would reread", reading_date: "May 12 2019")
ReadingChallenge.create!(book_title: "Dobry", comment: "interesting", reading_date: "May 13 2019")
ReadingChallenge.create!(book_title: "Tales From Silver Lands", comment: "so close to 30 books goal", reading_date: "May 14 2019")
ReadingChallenge.create!(book_title: "Shen of the Sea: Chinese Stories for Children", comment: "interesting look into chinese children book", reading_date: "May 15 2019")
ReadingChallenge.create!(book_title: "Waterless Mountain", comment: "… engaging", reading_date: "May 16 2019")
ReadingChallenge.create!(book_title: "Young Fu of the Upper Yangtze", comment: "… compelling evidence and logic…", reading_date: "May 17 2019")
ReadingChallenge.create!(book_title: "...And Now Miguel", comment: "… a wealth of great advice… clear, succinct, robust … compact and accessible…", reading_date: "May 18 2019")
ReadingChallenge.create!(book_title: "Shadow of a Bull", comment: "1 BOOK TO GO!", reading_date: "May 19 2019")


CouponCode.create!(code: "FlEMMINGDISCOUNT")

admin_account = Account.new(admin: true, avatar: "admin.png", email: "admin@admin.admin", password: "adminowl")
admin_account.save!

user_account = Account.new(admin:false, avatar: "empty_avatar", email: "testuser@email.com", password: "testuser")
user_account.save!